export default {
  homePath: '/',
  loginPath: '/auth/login',
  registerPath: '/auth/register',
  adminDashboardPath: '/admin/dashboard',
  landlordDashboardPath: '/landlord/dashboard',
  verifyPath: '/auth/verify',
  sendOtpPath: '/auth/send-otp',
  resetPasswordPath: '/auth/reset-password',
  profilePath: '/profile',
  postDetailUserPath: '/posts/:slug',
  contactRequestPath: '/contact-requests',
  maintenancePath: '/maintenance',
  myInvoicePath: '/my-invoices',
  settingPath: '/settings',
  washerPath: '/washers',
  myRoomPath: '/my-rooms',
  contractPath: '/contracts',
  roleAdmin: "admin",
  roleLandlord: "landlord",
  roleStaff: "staff",

}
